/**
 * Standard habit library.
 *
 * These presets are read-only templates — they are never stored directly.
 * When a user "adds" a preset, a new Habit is created from the template
 * with isPreset: true and the stable presetId preserved.
 *
 * Point values are standardised so scores remain comparable across users.
 */
import { PresetHabit, PresetCategory } from '../types';

export const PRESET_CATEGORIES: PresetCategory[] = [
  'Fitness',
  'Learning',
  'Focus',
  'Health',
  'Discipline',
  'Mindfulness',
];

export const PRESETS: PresetHabit[] = [
  // ─── FITNESS ─────────────────────────────────────────────────────────────
  {
    presetId: 'fitness-morning-run',
    name: 'Morning Run',
    points: 15,
    type: 'positive',
    identityCategory: 'athlete',
    category: 'Fitness',
  },
  {
    presetId: 'fitness-gym',
    name: 'Gym Session',
    points: 20,
    type: 'positive',
    identityCategory: 'athlete',
    category: 'Fitness',
  },
  {
    presetId: 'fitness-walk',
    name: 'Walk 30 Min',
    points: 8,
    type: 'positive',
    identityCategory: 'athlete',
    category: 'Fitness',
  },
  {
    presetId: 'fitness-yoga',
    name: 'Yoga',
    points: 12,
    type: 'positive',
    identityCategory: 'athlete',
    category: 'Fitness',
  },
  {
    presetId: 'fitness-stretch',
    name: 'Stretch / Mobility',
    points: 5,
    type: 'positive',
    identityCategory: 'athlete',
    category: 'Fitness',
  },
  {
    presetId: 'fitness-swim',
    name: 'Swim',
    points: 15,
    type: 'positive',
    identityCategory: 'athlete',
    category: 'Fitness',
  },
  {
    presetId: 'fitness-skip-workout',
    name: 'Skipped Workout',
    points: 15,
    type: 'negative',
    identityCategory: 'athlete',
    category: 'Fitness',
  },
  {
    presetId: 'fitness-sedentary',
    name: 'Sedentary All Day',
    points: 10,
    type: 'negative',
    identityCategory: 'athlete',
    category: 'Fitness',
  },

  // ─── LEARNING ────────────────────────────────────────────────────────────
  {
    presetId: 'learning-read-30',
    name: 'Read 30 Minutes',
    points: 12,
    type: 'positive',
    identityCategory: 'reader',
    category: 'Learning',
  },
  {
    presetId: 'learning-book-chapter',
    name: 'Finish a Chapter',
    points: 8,
    type: 'positive',
    identityCategory: 'reader',
    category: 'Learning',
  },
  {
    presetId: 'learning-study',
    name: 'Study Session (60 min)',
    points: 20,
    type: 'positive',
    identityCategory: 'scholar',
    category: 'Learning',
  },
  {
    presetId: 'learning-course',
    name: 'Online Course Lesson',
    points: 12,
    type: 'positive',
    identityCategory: 'scholar',
    category: 'Learning',
  },
  {
    presetId: 'learning-flashcards',
    name: 'Flashcard Practice',
    points: 8,
    type: 'positive',
    identityCategory: 'scholar',
    category: 'Learning',
  },
  {
    presetId: 'learning-skill',
    name: 'Practiced a Skill',
    points: 12,
    type: 'positive',
    identityCategory: 'scholar',
    category: 'Learning',
  },
  {
    presetId: 'learning-skipped-reading',
    name: 'Skipped Reading',
    points: 8,
    type: 'negative',
    identityCategory: 'reader',
    category: 'Learning',
  },
  {
    presetId: 'learning-no-study',
    name: 'No Study on a Study Day',
    points: 12,
    type: 'negative',
    identityCategory: 'scholar',
    category: 'Learning',
  },

  // ─── FOCUS ───────────────────────────────────────────────────────────────
  {
    presetId: 'focus-deep-work',
    name: 'Deep Work Block (90 min)',
    points: 20,
    type: 'positive',
    identityCategory: 'disciplined',
    category: 'Focus',
  },
  {
    presetId: 'focus-no-phone-morning',
    name: 'No Phone Before 9am',
    points: 10,
    type: 'positive',
    identityCategory: 'disciplined',
    category: 'Focus',
  },
  {
    presetId: 'focus-single-task',
    name: 'Single-Tasked All Day',
    points: 12,
    type: 'positive',
    identityCategory: 'disciplined',
    category: 'Focus',
  },
  {
    presetId: 'focus-plan-day',
    name: 'Planned Tomorrow',
    points: 8,
    type: 'positive',
    identityCategory: 'disciplined',
    category: 'Focus',
  },
  {
    presetId: 'focus-doom-scroll',
    name: 'Doom Scrolled',
    points: 12,
    type: 'negative',
    identityCategory: 'disciplined',
    category: 'Focus',
  },
  {
    presetId: 'focus-phone-in-bed',
    name: 'Phone in Bed',
    points: 8,
    type: 'negative',
    identityCategory: 'disciplined',
    category: 'Focus',
  },
  {
    presetId: 'focus-scattered',
    name: 'Reactive / Scattered Work',
    points: 10,
    type: 'negative',
    identityCategory: 'disciplined',
    category: 'Focus',
  },

  // ─── HEALTH ──────────────────────────────────────────────────────────────
  {
    presetId: 'health-sleep-8',
    name: '8 Hours Sleep',
    points: 15,
    type: 'positive',
    identityCategory: 'healthy',
    category: 'Health',
  },
  {
    presetId: 'health-water',
    name: 'Drank 2L Water',
    points: 8,
    type: 'positive',
    identityCategory: 'healthy',
    category: 'Health',
  },
  {
    presetId: 'health-no-alcohol',
    name: 'No Alcohol',
    points: 10,
    type: 'positive',
    identityCategory: 'healthy',
    category: 'Health',
  },
  {
    presetId: 'health-cooked-meal',
    name: 'Cooked a Meal',
    points: 8,
    type: 'positive',
    identityCategory: 'healthy',
    category: 'Health',
  },
  {
    presetId: 'health-poor-sleep',
    name: 'Poor Sleep / Late Night',
    points: 15,
    type: 'negative',
    identityCategory: 'healthy',
    category: 'Health',
  },
  {
    presetId: 'health-junk-food',
    name: 'Junk Food',
    points: 10,
    type: 'negative',
    identityCategory: 'healthy',
    category: 'Health',
  },
  {
    presetId: 'health-alcohol',
    name: 'Drank Alcohol',
    points: 12,
    type: 'negative',
    identityCategory: 'healthy',
    category: 'Health',
  },

  // ─── DISCIPLINE ──────────────────────────────────────────────────────────
  {
    presetId: 'disc-wake-on-time',
    name: 'Woke Up On Time',
    points: 12,
    type: 'positive',
    identityCategory: 'disciplined',
    category: 'Discipline',
  },
  {
    presetId: 'disc-no-snooze',
    name: 'No Snooze',
    points: 8,
    type: 'positive',
    identityCategory: 'disciplined',
    category: 'Discipline',
  },
  {
    presetId: 'disc-top-priority',
    name: 'Completed Top Priority',
    points: 20,
    type: 'positive',
    identityCategory: 'disciplined',
    category: 'Discipline',
  },
  {
    presetId: 'disc-cold-shower',
    name: 'Cold Shower',
    points: 10,
    type: 'positive',
    identityCategory: 'disciplined',
    category: 'Discipline',
  },
  {
    presetId: 'disc-procrastinate',
    name: 'Procrastinated',
    points: 15,
    type: 'negative',
    identityCategory: 'disciplined',
    category: 'Discipline',
  },
  {
    presetId: 'disc-snooze',
    name: 'Hit Snooze',
    points: 8,
    type: 'negative',
    identityCategory: 'disciplined',
    category: 'Discipline',
  },
  {
    presetId: 'disc-missed-commitment',
    name: 'Missed a Commitment',
    points: 12,
    type: 'negative',
    identityCategory: 'disciplined',
    category: 'Discipline',
  },

  // ─── MINDFULNESS ─────────────────────────────────────────────────────────
  {
    presetId: 'mind-meditate',
    name: 'Meditation (10+ min)',
    points: 15,
    type: 'positive',
    identityCategory: 'mindful',
    category: 'Mindfulness',
  },
  {
    presetId: 'mind-breathwork',
    name: 'Breathwork',
    points: 8,
    type: 'positive',
    identityCategory: 'mindful',
    category: 'Mindfulness',
  },
  {
    presetId: 'mind-gratitude',
    name: 'Gratitude Practice',
    points: 8,
    type: 'positive',
    identityCategory: 'mindful',
    category: 'Mindfulness',
  },
  {
    presetId: 'mind-no-news',
    name: 'No News / Social Media Hour',
    points: 10,
    type: 'positive',
    identityCategory: 'mindful',
    category: 'Mindfulness',
  },
  {
    presetId: 'mind-journal',
    name: 'Evening Journal',
    points: 10,
    type: 'positive',
    identityCategory: 'mindful',
    category: 'Mindfulness',
  },
  {
    presetId: 'mind-reactive',
    name: 'Reacted Emotionally',
    points: 10,
    type: 'negative',
    identityCategory: 'mindful',
    category: 'Mindfulness',
  },
  {
    presetId: 'mind-skipped',
    name: 'Skipped Mindfulness Practice',
    points: 8,
    type: 'negative',
    identityCategory: 'mindful',
    category: 'Mindfulness',
  },
];
